#!/bin/bash

shopt -s expand_aliases
source ~/.bash_aliases

#cmd=("$@");
#echo "Running command ${cmd[*]}";

if [ $# -ne 0 ]; then
  cmd=$@;
  echo "Running command $cmd";
  eval $cmd;
else
  echo "Canceled"
  exit 1
fi

